### ISSUE TITLE
Lack of sudo in the image

### ISSUE THREAD

**Issue by nicl-nno** [arunvelsriram/utils#12]
Hi,

I tried to use the image, but there is no **sudo** and I do not know the password to use the **su**.
However, root access is required for me.

Can you help with this issue?

**Comment by arunvelsriram** [comment]
you could run the container using root user

```
docker run --rm -it --user root arunvelsriram/utils bash
```

**Comment by nicl-nno** [comment]
It works, thank you!

**Comment by tianjianchn** [comment]
How about k8s? `kubectl run` doesn't have `--user` option.
